use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :artheon, Artheon.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [host: {:system, "DOMAIN"}, port: {:system, "SSL_PORT"}],
  force_ssl: [port: {:system, "SSL_PORT"}],
  environment: System.get_env("MIX_ENV") || "prod",
  https: [
      port: {:system, "SSL_PORT"},
      otp_app: :eyr,
      keyfile: "/etc/letsencrypt/live/#{System.get_env(~s(DOMAIN))}/privkey.pem",
      certfile: "/etc/letsencrypt/live/#{System.get_env(~s(DOMAIN))}/cert.pem"
  ],
  cache_static_manifest: "priv/static/manifest.json",
  secret_key_base: {:system, "SECRET"}

# Do not print debug messages in production
config :logger, level: :info

# ## SSL Support
#
# To get SSL working, you will need to add the `https` key
# to the previous section and set your `:url` port to 443:
#
#     config :artheon, Artheon.Endpoint,
#       ...
#       url: [host: "example.com", port: 443],
#       https: [port: 443,
#               keyfile: System.get_env("SOME_APP_SSL_KEY_PATH"),
#               certfile: System.get_env("SOME_APP_SSL_CERT_PATH")]
#
# Where those two env variables return an absolute path to
# the key and cert in disk or a relative path inside priv,
# for example "priv/ssl/server.key".
#
# We also recommend setting `force_ssl`, ensuring no data is
# ever sent via http, always redirecting to https:
#
#     config :artheon, Artheon.Endpoint,
#       force_ssl: [hsts: true]
#
# Check `Plug.SSL` for all available options in `force_ssl`.

# ## Using releases
#
# If you are doing OTP releases, you need to instruct Phoenix
# to start the server for all endpoints:
#
#     config :phoenix, :serve_endpoints, true
#
# Alternatively, you can configure exactly which server to
# start per endpoint:
#
#     config :artheon, Artheon.Endpoint, server: true
#

# Finally import the config/prod.secret.exs
# which should be versioned separately.
# import_config "prod.secret.exs"
